version = 0.1

[dev.global.parameters]
stack_name = "brickhub-dev"
region = "us-east-1"

[dev.build.parameters]
cached = true
parallel = true

[dev.deploy.parameters]
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides = "Environment=\"dev\" BricksetSecretArn=\"arn:aws:secretsmanager:us-east-1:255358858742:secret:brickset-iujkYw\""
s3_prefix = "brickhub-dev"
profile = "brickhub-dev"
image_repositories = []

[dev.local_start_api.parameters]
region = "us-east-1"
profile = "brickhub-dev"
parameter_overrides = "Environment=dev BricksetSecretArn=arn:aws:secretsmanager:us-east-1:255358858742:secret:brickset-iujkYw"

[dev.sync.parameters]
watch = true

[default.deploy.parameters]
stack_name = "brickhub-dev"
resolve_s3 = true
s3_prefix = "brickhub-dev"
profile = "brickhub-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"dev\" BricksetSecretArn=\"arn:aws:secretsmanager:us-east-1:255358858742:secret:brickset-iujkYw\" ScrapeDoSecretArn=\"arn:aws:secretsmanager:us-east-1:255358858742:secret:scrapedo-bXDDSV\" IosCallbackUrl=\"brickhub://auth/callback\" CognitoDomainPrefix=\"brickhub-dev\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
