import { expect, it, vi } from "vitest";
import type { APIGatewayProxyEventV2 } from "aws-lambda";
import { getAmazonOffersRoute } from "../../../../src/modules/amazon-offers/get-amazon-offers.route";
import { GetAmazonOffersController } from "../../../../src/modules/amazon-offers/get-amazon-offers.controller";
import { GetAmazonOffersService } from "../../../../src/modules/amazon-offers/get-amazon-offers.service";
function event(headers: Record<string, string> = {}, sub?: string): APIGatewayProxyEventV2 { return { headers, requestContext: { requestId: "request-1", http: { method: "GET" }, authorizer: { jwt: { claims: sub === undefined ? {} : { sub } } } } } as unknown as APIGatewayProxyEventV2; }
it("requires a valid Bearer and verified sub before constructing dependencies", async () => { const createController = vi.fn(); const response = await getAmazonOffersRoute(event(), { createController }); expect(response.statusCode).toBe(401); expect(JSON.parse(response.body ?? "")).toMatchObject({ code: "UNAUTHENTICATED" }); expect(createController).not.toHaveBeenCalled(); });
it("serves a valid authenticated request and logs only result metadata", async () => { const log = vi.fn(); const response = await getAmazonOffersRoute(event({ authorization: "Bearer session" }, "user-1"), { createController: () => new GetAmazonOffersController(new GetAmazonOffersService({ list: async () => [] })), log, now: () => 1 }); expect(response.statusCode).toBe(200); expect(log).toHaveBeenCalledWith({ event: "amazon_offers_completed", requestId: "request-1", durationMs: 0, resultCount: 0 }); });
it("logs a safe code when the authenticated controller fails", async () => { const log = vi.fn(); const response = await getAmazonOffersRoute(event({ authorization: "Bearer session" }, "user-1"), { createController: () => { throw new Error("private table"); }, log }); expect(response.statusCode).toBe(500); expect(response.body).not.toContain("private table"); expect(log).toHaveBeenCalledWith(expect.objectContaining({ event: "amazon_offers_failed", code: "INTERNAL_ERROR" })); });
