import { expect,it,vi } from "vitest";
import { getShoppingProductRoute } from "../../../../src/modules/shopping/get-shopping-product.route";
import { GetShoppingProductController } from "../../../../src/modules/shopping/get-shopping-product.controller";
import { GetShoppingProductService } from "../../../../src/modules/shopping/get-shopping-product.service";
import { productEvent,productSample } from "../../../fixtures/shopping/product-helpers";
it.each([undefined,"","Bearer ","Basic x","Bearer a,b"])("rejects auth %s before dependencies",async authorization=>{const event=productEvent();event.headers={authorization};const createController=vi.fn();expect((await getShoppingProductRoute(event,{createController,log:()=>{}})).statusCode).toBe(401);expect(createController).not.toHaveBeenCalled();});
it("rejects missing trusted sub and duplicate auth headers",async()=>{for(const event of [productEvent(undefined,false),{...productEvent(),headers:{authorization:"Bearer x",Authorization:"Bearer y"}}]){const createController=vi.fn();expect((await getShoppingProductRoute(event,{createController,log:()=>{}})).statusCode).toBe(401);expect(createController).not.toHaveBeenCalled();}});
it.each(["q=x","catalog_id=1","catalog_id=1&q=x&q=y","catalog_id=1&q=x&load_all_stores=false","catalog_id=1&q=x&more_stores=true","catalog_id=1&q=x&token=foo","catalog_id=0&q=x"])("rejects %s before creating service",async raw=>{const createService=vi.fn();expect((await new GetShoppingProductController(createService).handle(raw)).statusCode).toBe(400);expect(createService).not.toHaveBeenCalled();});
it("logs safe metadata and ignores logger failure",async()=>{const log=vi.fn().mockImplementation(()=>{throw new Error("logger");});const response=await getShoppingProductRoute(productEvent(),{createController:()=>new GetShoppingProductController(()=>new GetShoppingProductService({getProduct:vi.fn().mockResolvedValue(productSample())})),log});expect(response.statusCode).toBe(200);expect(log.mock.calls[0]?.[0]).toMatchObject({event:"shopping_product_completed",storeCount:33});expect(JSON.stringify(log.mock.calls)).not.toContain("LEGO");expect(JSON.stringify(log.mock.calls)).not.toContain("6789801949246787910");});
