import { expect,it,vi } from "vitest";
import { ScrapeDoClient } from "../../../../src/modules/shopping/scrapedo.client";
import { productSample,productQuery,deadline } from "../../../fixtures/shopping/product-helpers";
async function execute(data:unknown,headers?:HeadersInit){return new ScrapeDoClient(vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify(data),{headers}))).getProduct({apiKey:"fake-provider-key"},productQuery,deadline());}
it("rejects truncation header regardless of case/whitespace",async()=>{await expect(execute(productSample(),{"Scrape.do-Auto-Page-Truncated":" TRUE "})).rejects.toMatchObject({code:"UPSTREAM_INVALID_RESPONSE"});});
it.each(["cursor",1,false,{},[]].map(value=>[value]))("rejects continuation cursor %j instead of following it",async next_page_token=>{const d=productSample();await expect(execute({...d,product_results:{...d.product_results,next_page_token}})).rejects.toMatchObject({code:"UPSTREAM_INVALID_RESPONSE"});});
it.each([undefined,null,""])("accepts exhausted cursor %s and excludes unknowns",async next_page_token=>{const d=productSample();expect(await execute({...d,product_results:{...d.product_results,next_page_token,unknown:"private"},unknown:"private"})).toEqual(d);});
it.each(["javascript:alert(1)","https://user:pass@example.com"])("rejects unsafe link %s",async link=>{const d=productSample();d.product_results.stores[0]!.link=link;await expect(execute(d)).rejects.toMatchObject({code:"UPSTREAM_INVALID_RESPONSE"});});
it("redacts credentials in store URLs and preserves ordinary original URLs",async()=>{const d=productSample();d.product_results.stores[0]!.link="https://shop.example/item?token=fake-provider-key&keep=1";const result=await execute(d);expect(result.product_results.stores[0]?.link).toBe("https://shop.example/item?keep=1");expect(result.product_results.stores[1]?.link).toBe(d.product_results.stores[1]?.link);});
it.each(["fake-provider-key","fake%2Dprovider%2Dkey"])("rejects key reflection %s",async title=>{const d=productSample();d.product_results.title=title;await expect(execute(d)).rejects.toMatchObject({code:"UPSTREAM_INVALID_RESPONSE"});});
it("rejects base64 credential reflection in allowed image",async()=>{const d=productSample();d.product_results.stores[0]!.thumbnail="data:image/png;base64,"+Buffer.from("fake-provider-key").toString("base64");await expect(execute(d)).rejects.toMatchObject({code:"UPSTREAM_INVALID_RESPONSE"});});
