import { expect,it,vi } from "vitest";
import { getShoppingProductRoute } from "../../../src/modules/shopping/get-shopping-product.route";
import { GetShoppingProductController } from "../../../src/modules/shopping/get-shopping-product.controller";
import { GetShoppingProductService } from "../../../src/modules/shopping/get-shopping-product.service";
import { productEvent,productSample,productQuery } from "../../fixtures/shopping/product-helpers";
it("serves authorized product via layered HTTP boundary",async()=>{const getProduct=vi.fn().mockResolvedValue(productSample());const response=await getShoppingProductRoute(productEvent(),{createController:()=>new GetShoppingProductController(()=>new GetShoppingProductService({getProduct})),log:()=>{}});expect(response.statusCode).toBe(200);expect(JSON.parse(response.body??"{}")).toEqual({status:"success",data:productSample()});expect(getProduct).toHaveBeenCalledTimes(1);expect(getProduct.mock.calls[0]?.[0]).toEqual(productQuery);});

import { ScrapeDoRepository } from "../../../src/modules/shopping/scrapedo.repository";
import { ScrapeDoClient } from "../../../src/modules/shopping/scrapedo.client";
import { SecretsManagerScrapeDoCredentialsProvider } from "../../../src/modules/shopping/scrapedo-secret.provider";
it("uses all real layers with only SDK and fetch replaced",async()=>{const send=vi.fn().mockResolvedValue({SecretString:'{"SCRAPE_DO_API_KEY":"fixture-key"}'});const request=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify(productSample())));const repo=new ScrapeDoRepository(new SecretsManagerScrapeDoCredentialsProvider("test-arn",{send}),new ScrapeDoClient(request));const response=await getShoppingProductRoute(productEvent(),{createController:()=>new GetShoppingProductController(()=>new GetShoppingProductService(repo)),log:()=>{}});expect(response.statusCode).toBe(200);expect(JSON.parse(response.body??"{}").data).toEqual(productSample());expect(send).toHaveBeenCalledTimes(1);expect(request).toHaveBeenCalledTimes(1);expect(response.body).not.toContain("fixture-key");});
it("exported handler rejects anonymous event without network",async()=>{const {handler}=await import("../../../src/handlers/get-shopping-product");const fetchSpy=vi.spyOn(globalThis,"fetch");const consoleSpy=vi.spyOn(console,"info").mockImplementation(()=>{});try{expect(await handler(productEvent(undefined,false),{} as never,()=>{})).toMatchObject({statusCode:401});expect(fetchSpy).not.toHaveBeenCalled();}finally{fetchSpy.mockRestore();consoleSpy.mockRestore();}});
it("secret2s deadline stops product before provider call",async()=>{vi.useFakeTimers();try{const send=vi.fn().mockImplementation(()=>new Promise(()=>{}));const getProduct=vi.fn();const repo=new ScrapeDoRepository(new SecretsManagerScrapeDoCredentialsProvider("test-arn",{send}),{search:vi.fn(),getProduct});const pending=getShoppingProductRoute(productEvent(),{createController:()=>new GetShoppingProductController(()=>new GetShoppingProductService(repo)),log:()=>{}});await vi.advanceTimersByTimeAsync(2000);expect((await pending).statusCode).toBe(500);expect(getProduct).not.toHaveBeenCalled();expect(send).toHaveBeenCalledTimes(1);}finally{vi.useRealTimers();}});
it("search remains independent from the product method",async()=>{const {searchShoppingRoute}=await import("../../../src/modules/shopping/search-shopping.route");const {SearchShoppingController}=await import("../../../src/modules/shopping/search-shopping.controller");const {SearchShoppingService}=await import("../../../src/modules/shopping/search-shopping.service");const {sample,shoppingEvent}=await import("../../fixtures/shopping/helpers");const getProduct=vi.fn();const catalog={search:vi.fn().mockResolvedValue(sample()),getProduct};const response=await searchShoppingRoute(shoppingEvent(),{createController:()=>new SearchShoppingController(()=>new SearchShoppingService(catalog)),log:()=>{}});expect(JSON.parse(response.body??"{}")).toEqual({status:"success",data:sample()});expect(getProduct).not.toHaveBeenCalled();});
