import { expect, it } from "vitest";
import type { APIGatewayProxyEventV2 } from "aws-lambda";
import { getAmazonOffersRoute } from "../../../src/modules/amazon-offers/get-amazon-offers.route";
import { GetAmazonOffersController } from "../../../src/modules/amazon-offers/get-amazon-offers.controller";
import { GetAmazonOffersService } from "../../../src/modules/amazon-offers/get-amazon-offers.service";
import { initialCards } from "../../fixtures/amazon-offers/amazon-offer-cards";
function event(requestId: string): APIGatewayProxyEventV2 { return { headers: { authorization: "Bearer fixture-token" }, requestContext: { requestId, http: { method: "GET" }, authorizer: { jwt: { claims: { sub: "fixture-user" } } } } } as unknown as APIGatewayProxyEventV2; }
it("serves the initial catalog with authorization", async () => { const response = await getAmazonOffersRoute(event("request-1"), { createController: () => new GetAmazonOffersController(new GetAmazonOffersService({ list: async () => initialCards.map(({ title, discount, url, image }) => ({ title, discount, url, image })) })), log: () => {} }); const body = JSON.parse(response.body ?? "{}"); expect(response.statusCode).toBe(200); expect(body.data.offers).toHaveLength(5); expect(body.data.offers[0]).toMatchObject({ title: "LEGO Señor de los Anillos", discount: "hasta 22%" }); expect(body.data.offers[0]).not.toHaveProperty("amazonOfferId"); });
it("keeps an empty catalog distinct from a failed read", async () => { const empty = await getAmazonOffersRoute(event("request-2"), { createController: () => new GetAmazonOffersController(new GetAmazonOffersService({ list: async () => [] })), log: () => {} }); const failed = await getAmazonOffersRoute(event("request-2"), { createController: () => new GetAmazonOffersController(new GetAmazonOffersService({ list: async () => { throw new Error("bad item"); } })), log: () => {} }); expect(empty.statusCode).toBe(200); expect(JSON.parse(empty.body ?? "")).toEqual({ status: "success", data: { offers: [] } }); expect(failed.statusCode).toBe(500); expect(failed.body).not.toContain("bad item"); });
